### ISSUE TITLE
Fully implemented Accounting view

### ISSUE THREAD

**Issue by JustinLohKingWei** [serum-390/soen390-team16-godzilla#75] opened 2021-02-03 23:29 UTC
**Is your feature request related to a problem? Please describe.**
I am unable to view the credit/debit information on my financial account balance

**Describe the solution you'd like**
I would like a organised view to view the credit/debit information on my financial account balance

**Comment by instamine** [comment] 2021-03-19 03:44
Duplicate of #54

**Comment by instamine** [comment] 2021-03-19 03:45
#54

**Comment by instamine** [comment] 2021-03-19 03:45
#54

**Closed by instamine** 2021-03-19 03:45 UTC
Labels: Frontend, enhancement
